Crude Validation System Implementation
Innoactive/Creator pull request #177
Opened 2020-09-24 15:38 UTC by SimonTheSourcerer

### Description
Validation system, which does allow different ways of validating course entities.

### Type of change
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] UnitTests written

### How Has This Been Tested?
To be discussed

**Test Configuration**:
https://github.com/Innoactive/Basic-Interaction-Component/tree/feature/validation-trng-374
https://github.com/Innoactive/Basic-Conditions-And-Behaviors/tree/feature/validation-trng-374
https://github.com/Innoactive/TextToSpeech-Component/tree/feature/validation-trng-374

2020-09-28 08:47 UTC, Gusinuhe requested changes

2020-09-28 08:47 UTC, Gusinuhe commented on Editor/CourseValidation/ValidationScopes/BaseValidationScope.cs
> +        if (!(context is TContext))
```suggestion
        if ((context is TContext) == false)
```

2020-09-28 08:47 UTC, Gusinuhe commented on Editor/CourseValidation/ValidationScopes/BaseValidationScope.cs
> +    /// Run your validators here.
Is this telling me what it does or what to do? 🤔

2020-09-28 08:47 UTC, Gusinuhe commented on Editor/CourseValidation/ValidationScopes/BaseValidationScope.cs
> +    public abstract class BaseValidationScope<T, TContext> : IValidationScope where TContext : IContext
The indentation in this class is very odd.

2020-09-28 08:47 UTC, Gusinuhe commented on Editor/CourseValidation/ValidationScopes/ChapterValidationScope.cs
> +        protected override List<ValidationReportEntry> InternalValidate(IChapter chapter)
```suggestion
        /// <inheritdoc />
        protected override List<ValidationReportEntry> InternalValidate(IChapter chapter)
```

2020-09-28 08:47 UTC, Gusinuhe commented on Editor/CourseValidation/ValidationScopes/CourseValidationScope.cs
> +        protected override List<ValidationReportEntry> InternalValidate(ICourse course)
```suggestion
        /// <inheritdoc />
        protected override List<ValidationReportEntry> InternalValidate(ICourse course)
```

2020-09-28 08:47 UTC, Gusinuhe commented on Editor/CourseValidation/ValidationScopes/StepValidationScope.cs
> +        protected override List<ValidationReportEntry> InternalValidate(IStep step)
```suggestion
        /// <inheritdoc />
        protected override List<ValidationReportEntry> InternalValidate(IStep step)
```

2020-09-28 08:47 UTC, Gusinuhe commented on Editor/CourseValidation/Validator/BaseValidator.cs
> +                if (!(context is TContext))
```suggestion
                if ((context is TContext) == false)
```

2020-09-28 08:47 UTC, Gusinuhe commented on Editor/CourseValidation/Validator/BaseValidator.cs
> +                        $"Context given to this validation scope is wrong it is {context.GetType()} but should be {typeof(TContext).Name}");
Perhaps informing where this happens helps to debug the problem:

```suggestion
                        $"Context given to this validation {GetType().Name} scope is wrong it is {context.GetType()} but should be {typeof(TContext).Name}");
```

2020-09-28 08:47 UTC, Gusinuhe commented on Editor/CourseValidation/Validator/StepAttributeValidator.cs
> +    /// Checks a Steps data for attributes which implement <see cref="IAttributeValidator"/> and runs there valiation.
```suggestion
    /// Checks a Step data for attributes which implement <see cref="IAttributeValidator"/> and runs there valiation.
```

2020-09-28 08:47 UTC, Gusinuhe commented on Editor/CourseValidation/Validator/StepAttributeValidator.cs
> +        protected override List<ValidationReportEntry> InternalValidate(IStep step)
```suggestion
        /// <inheritdoc/>
        protected override List<ValidationReportEntry> InternalValidate(IStep step)
```

2020-09-28 08:47 UTC, Gusinuhe commented on Editor/CourseValidation/Validator/StepConnectionValidator.cs
> +        protected override List<ValidationReportEntry> InternalValidate(IChapter chapter)
```suggestion
        /// <inheritdoc/>
        protected override List<ValidationReportEntry> InternalValidate(IChapter chapter)
```

2020-09-28 08:47 UTC, Gusinuhe commented on Editor/EditorReflectionUtils.cs
> +using JetBrains.Annotations;
Is this required? Many users won't use Rider but Visual Studio.

2020-09-28 08:47 UTC, Gusinuhe commented on Editor/EditorReflectionUtils.cs
> +        public static IEnumerable<MemberInfo> GetAllFieldsAndProperties(object value)
Missing docs

2020-09-28 08:47 UTC, Gusinuhe commented on Editor/UI/Windows/TrainingMenuView.cs
> +                    }
What are we going to do about this?

2020-09-28 08:47 UTC, Gusinuhe commented on Runtime/CourseValidation/CheckForColliderAttribute.cs
> +        public CheckForColliderAttribute() : base(typeof(BoxCollider), typeof(SphereCollider), typeof(CapsuleCollider), typeof(MeshCollider), typeof(Collider))
Why not simply?
```suggestion
        public CheckForColliderAttribute() : base(typeof(Collider))
```

2020-09-28 08:47 UTC, Gusinuhe commented on Runtime/CourseValidation/CheckForComponentAttribute.cs
> +            if (value == null || !(value is UniqueNameReference reference))
Please, stick to the code convention.

```suggestion
            if (value == null || (value is UniqueNameReference reference) == false)
```

2020-09-28 08:47 UTC, Gusinuhe commented on Runtime/CourseValidation/RequiredAttribute.cs
> +                message = "This variable is required";
Which variable? 🤔
The same for all other messages.

2020-09-28 08:47 UTC, Gusinuhe commented on Runtime/SceneObjects/ObjectReference.cs
> +        public bool IsEmpty()
Missing docs

2020-09-28 08:47 UTC, Gusinuhe commented on Runtime/Utils/Audio/ResourceAudio.cs
> +        public bool IsEmpty()
Missing docs

2020-09-28 08:47 UTC, Gusinuhe commented on Runtime/Utils/ICanBeEmpty.cs
> +    public interface ICanBeEmpty
So, sad 😕

2020-09-29 13:54 UTC, Gusinuhe commented on Editor/CourseValidation/Context/MemberInfoContext.cs
> +        public MemberInfo MemberInfo { get; }
Since it is not used anywhere outside this class and I have no clue what it actually does, I'll just change it to internal 😎

2020-09-30 08:32 UTC, Gusinuhe commented on Runtime/CourseValidation/CheckForColliderAttribute.cs
> +        public CheckForColliderAttribute() : base(typeof(BoxCollider), typeof(SphereCollider), typeof(CapsuleCollider), typeof(MeshCollider), typeof(Collider))
It does require to specify each collider type 😞

2020-09-30 08:44 UTC, aleksei-korolev commented on Editor/CourseValidation/Context/IContext.cs
> +        bool IsSelectable { get; }
You could separate Select() method to ISelectableContext interface to enforce that.

2020-09-30 11:35 UTC, Gusinuhe commented
A cleaned a few things, applied some suggestions, and added documentation.

There is still some nice to have that could be addressed either now or in the future:

- Implementations of the `Select` method for `EntityContext<T>` objects (`BehaviorContext`, `ChapterContext`, `ConditionContext`, `CourseContext`, and `TransitionContext`). *
- The method `ContextResolver.FindContext(IEntity entity, ICourse course)` could be optimized.
- The method `BaseValidationScope<T, TContext>.GetValidators()` could be optimized. **
- The constructor of `ValidationHandler` could be optimized. **
- Make internal whatever can be internal.
- Figure out how to trigger the validation system for the whole course (maybe with the UI implementation) and remove the testing button.

* Should be implemented when we added graphic support to the validation system.
** I think @SimonTheSourcerer wanted to address these.

2020-09-30 13:16 UTC, tomwim requested changes

2020-09-30 13:16 UTC, tomwim commented on Runtime/CourseValidation/CheckForComponentAttribute.cs
> +    /// Checks if the referenced GameObject has at least one of the listed Type added as Component.
```suggestion
    /// Checks if the referenced GameObject has at least one of the listed Types added as Component.
```

2020-09-30 13:16 UTC, tomwim commented on Runtime/CourseValidation/CheckForComponentAttribute.cs
> +        /// List of required components types.
```suggestion
        /// List of required components.
```

2020-09-30 13:16 UTC, tomwim commented on Runtime/CourseValidation/IAttributeValidator.cs
> +        /// <param name="message">Message which will be used if there is an problem.</param>
```suggestion
        /// <param name="message">Message which will be used if there is a problem.</param>
```

2020-09-30 14:19 UTC, tomwim commented
After discussing with @Gusinuhe the architecture more we agreed that we are not too fond of the [Required] attribute for variables since it is not really backwards compatible and also is additional effort for template developers. We could not come up with the perfect solution that solves that issue but @Gusinuhe will think about something and will create a proposal.
One option would be too create an [Optional] attribute instead which does not help with the backwards compatibility but with the effort for developers since it should be less common than required.

2020-09-30 14:21 UTC, Gusinuhe commented on Editor/CourseValidation/Context/IContextResolver.cs
> +    /// Allows to resolve a <see cref="IContext"/> out of a given <see cref="IEntity"/>.
```suggestion
    /// Retrieves <see cref="IContext"/> from any provided <see cref="IEntity"/>.
```

2020-09-30 14:24 UTC, Gusinuhe commented on Editor/CourseValidation/ValidationScopes/StepValidationScope.cs
> +    /// Validation scope for steps.
```suggestion
    /// Validation scope for objects of type <see cref="IStep"/>.
```

2020-10-02 08:45 UTC, tomwim requested changes

2020-10-02 08:45 UTC, tomwim commented on Runtime/CourseValidation/IAttributeValidator.cs
> +        /// <returns>Return true if the validation fails for the given object.</returns>
I feel that returning true when the validation fails is not very intuitive. First of all it is checking if the attribute is valid and not invalid, right?

2020-10-07 10:52 UTC, closed without merging