docs: replace TBD with a meaningful message
Innoactive/Creator pull request #178
Opened 2020-10-02 10:35 UTC by aleksei-korolev

### Description

Replace "TBD" in dev's docu in chapters under construction with meaningful messages

### Type of change

- [X] This change requires a documentation update

### How Has This Been Tested?

I had read it out loud and clicked the links.

### Checklist

- [X] My code follows the [Coding Conventions](#coding-conventions)
- [X] I have performed a self-review of my code
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] New and existing unit tests pass locally with my changes

2020-10-02 10:41 UTC, burnedikt reviewed
You could also add a link to the file on github so someone with knowledge can create the documentation. Oftentimes seen in documentation of open source projects with a "Improve this Doc" Button. Also [supported by docFX](https://dotnet.github.io/docfx/tutorial/docfx.exe_user_manual.html#322-reserved-metadata)

2020-10-08 08:16 UTC, SimonTheSourcerer requested changes

2020-10-08 08:16 UTC, SimonTheSourcerer commented on .Documentation/articles/developer/TBD-02-editor-configuration.md
> +This is a topic that we want to write about, but we just had no time for it yet. You can take a look at our [API documentation](https://developers.innoactive.de/documentation/creator/v2.4.1/api/Innoa
```suggestion
This is a topic that we want to write about, but we just had no time for it yet. You can take a look at our [API documentation](https://developers.innoactive.de/documentation/creator/latest/api/Innoactive.CreatorEditor.Configuration.html) instead and then ask your questions in our [community](http://innoactive.io/creator/community). One of us developers will directly respond.
```

2020-10-08 08:16 UTC, SimonTheSourcerer commented on .Documentation/articles/developer/TBD-03-training-modes.md
> +This is a topic that we want to write about, but we just had no time for it yet. You can take a look at our [API documentation](https://developers.innoactive.de/documentation/creator/v2.4.1/api/Innoa
```suggestion
This is a topic that we want to write about, but we just had no time for it yet. You can take a look at our [API documentation](https://developers.innoactive.de/documentation/creator/latest/api/Innoactive.Creator.Core.Configuration.Modes.html) instead and then ask your questions in our [community](http://innoactive.io/creator/community). One of us developers will directly respond.
```

2020-10-08 08:16 UTC, SimonTheSourcerer commented on .Documentation/articles/developer/TBD-04-configurators.md
> +This is a topic that we want to write about, but we just had no time for it yet. You can take a look at our [API documentation](https://developers.innoactive.de/documentation/creator/v2.4.1/api/Innoa
```suggestion
This is a topic that we want to write about, but we just had no time for it yet. You can take a look at our [API documentation](https://developers.innoactive.de/documentation/creator/latest/api/Innoactive.Creator.Core.Entity-1.html#Innoactive_Creator_Core_Entity_1_GetConfigurator) instead and then ask your questions in our [community](http://innoactive.io/creator/community). One of us developers will directly respond.
```

2020-10-08 08:16 UTC, SimonTheSourcerer commented on .Documentation/articles/developer/TBD-05-mode-parameters.md
> +This is a topic that we want to write about, but we just had no time for it yet. You can take a look at our [API documentation](https://developers.innoactive.de/documentation/creator/v2.4.1/api/Innoa
```suggestion
This is a topic that we want to write about, but we just had no time for it yet. You can take a look at our [API documentation](https://developers.innoactive.de/documentation/creator/latest/api/Innoactive.Creator.Core.Configuration.Modes.ModeParameter-1.html) instead and then ask your questions in our [community](http://innoactive.io/creator/community). One of us developers will directly respond.
```

2020-10-08 08:16 UTC, SimonTheSourcerer commented on .Documentation/articles/developer/TBD-06-localization.md
> +This is a topic that we want to write about, but we just had no time for it yet. You can take a look at our [API documentation](https://developers.innoactive.de/documentation/creator/v2.4.1/api/Innoa
```suggestion
This is a topic that we want to write about, but we just had no time for it yet. You can take a look at our [API documentation](https://developers.innoactive.de/documentation/creator/latest/api/Innoactive.Creator.Core.Internationalization.html) instead and then ask your questions in our [community](http://innoactive.io/creator/community). One of us developers will directly respond.
```

2020-10-08 08:17 UTC, SimonTheSourcerer commented
I would like to just merge it after fixing the version thing because it's definitely much better than before.

2020-10-12 12:58 UTC, Gusinuhe commented
When or where is it supposed to appear this `Improve this Doc` button?

2020-10-12 13:21 UTC, Maxsiom commented
I think docFX does render it automatically.

2020-10-12 13:38 UTC, Maxsiom commented
https://dotnet.github.io/docfx/tutorial/docfx.exe_user_manual.html#322-reserved-metadata
If you look there it is on the right site above the content.

2020-10-12 13:49 UTC, burnedikt commented
> When or where is it supposed to appear this `Improve this Doc` button?

was just an idea, not a must. Enabling this should be as easy as defining `_gitContribute` in the `docfx.json` as indicated [here](https://dotnet.github.io/docfx/tutorial/docfx.exe_user_manual.html#322-reserved-metadata) but I am unsure if it will also require template changes as well to show that button / link. Can also be a separate PR.

2020-10-12 13:59 UTC, Gusinuhe commented
I ask because I built the docs and I didn't find the button anywhere 🤔

2020-10-12 14:00 UTC, Maxsiom commented
I put it into the meta data of our `docfx.json`. So I think it will now render it as soon as it is build. :)

2020-10-16 09:17 UTC, SimonTheSourcerer submitted a review, later dismissed

2020-10-16 09:20 UTC, tomwim requested changes

2020-10-16 09:20 UTC, tomwim commented on .Documentation/articles/developer/TBD-06-localization.md
> +Besides, you can take a look at our [API documentation](https://developers.innoactive.de/documentation/creator/latest/api/Innoactive.Creator.Core.Internationalization.html) instead and then ask your
```suggestion
Besides, you can take a look at our [API documentation](https://developers.innoactive.de/documentation/creator/latest/api/Innoactive.Creator.Core.Internationalization.html) instead and then ask your questions in our [community](http://innoactive.io/creator/community). One of our developers will directly respond.
```

2020-10-16 09:35 UTC, tomwim approved these changes

2020-10-16 12:19 UTC, tomwim approved these changes

2020-10-16 13:47 UTC, merged