The XR Setup page now always sets up the XR settings
Innoactive/Creator pull request #183
Opened 2020-10-20 09:48 UTC by Gusinuhe

### Description

**Fixes**: The XR Setup couldn't finish the process of setting up the desired target due to some timing limitations, in those scenarios, it used to show a pop up with instructions on how to finish the process manually. This PR makes sure the XR Setup page always finishes upsetting the desired XR SDK.

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

Create a new project, import the Creator, and select either Oculus or Windows MR in the XR Setup page. The process must always complete setting the desired target hardware.

2020-10-20 13:01 UTC, tomwim commented
I have the slight feeling that lint does not like "wip"

2020-10-20 13:04 UTC, Gusinuhe commented
> I have the slight feeling that lint does not like "wip"

Yeah, I also really like lint 😑

2020-10-20 13:40 UTC, Luphoxa commented
I tested this about 6 times and it did not come up. 👍 
As stated in slack, it would be nice if the "Wait until the setup is done" window wouldn't have an "understood" button that needs to be pressed in order to start the process, but instead if the window would stay there until the setup is really done :) 
If it's worth the effort to add this I will leave that decision to you :)

2020-10-20 13:41 UTC, tomwim requested changes

2020-10-20 13:41 UTC, tomwim commented on Editor/XRUtils/XRLoaderHelper.cs
> +        internal const string AttemptedToInitialized = "IsXRLoaderInitialized";
```suggestion
        internal const string AttemptedToInitialize = "IsXRLoaderInitialized";
```
I would say a better name is "IsXRLoaderInitialized", though

2020-10-20 15:40 UTC, tomwim commented
Also tested it and worked for me

2020-10-21 10:02 UTC, Maxsiom approved these changes

2020-10-21 15:13 UTC, tomwim approved these changes

2020-10-21 15:18 UTC, merged