feat: Improved help options in menu
Innoactive/Creator pull request #198
Opened 2020-11-11 10:22 UTC by SimonTheSourcerer

### Description
Help menu now also contains:
* Link to Community
* Link to Webinar
* Link to Documentation

2020-11-11 13:15 UTC, tomwim requested changes
Also tested it and all links work

2020-11-11 13:15 UTC, tomwim commented on Editor/UI/CreatorMenu/CommunityMenuEntry.cs
> +        /// Allows to open the URL to Innoactive community
```suggestion
        /// Allows to open the URL to Innoactive community.
```

2020-11-11 16:10 UTC, SimonTheSourcerer commented on Editor/UI/CreatorMenu/DocumentationMenuEntry.cs
> +
```suggestion
```

2020-11-11 16:29 UTC, Maxsiom approved these changes

2020-11-12 08:45 UTC, tomwim approved these changes

2020-11-12 08:46 UTC, merged