fix: added an warning about the new input sytem changes to the xr setup
Innoactive/Creator pull request #204
Opened 2020-11-20 14:48 UTC by SimonTheSourcerer

### Description
Added the warning for oculus and windows MR, not sure this is correct @Gusinuhe ?

2020-11-20 18:23 UTC, Gusinuhe requested changes

2020-11-20 18:23 UTC, Gusinuhe commented on Editor/UI/Wizard/Setup/XRSDKSetupPage.cs
> +                }
Actually, at the moment we show this warning, XR Interaction Toolkit is already installed, the message has no sense and can be hidden for users that either already has an XR configuration or select something else but Oculus and WindowsMR 😱

2020-11-26 15:22 UTC, Gusinuhe commented
This was not supposed to be merged :(

2020-11-30 09:21 UTC, Gusinuhe commented
This issue is already addressed in https://github.com/Innoactive/XR-Interaction-Component/pull/73, I suggest to close this PR.

2020-11-30 12:51 UTC, SimonTheSourcerer commented
So we close it?

2020-12-03 11:10 UTC, closed without merging