Feature/added active chapter
Innoactive/Creator pull request #233
Opened 2020-12-18 10:09 UTC by SimonTheSourcerer

2020-12-22 20:30 UTC, Maxsiom approved these changes

2021-01-11 13:04 UTC, tomwim requested changes

2021-01-11 13:04 UTC, tomwim commented on Runtime/Utils/LockObjectsOnSceneStart.cs.meta
> +guid: 3f6a9c6a675d6234790c91f6f15a4c0b
Why is this file changed? 🤔

2021-01-11 14:02 UTC, tomwim approved these changes

2021-01-11 14:11 UTC, merged