Feature/emtpy workflow show instructions
Innoactive/Creator pull request #237
Opened 2020-12-21 14:27 UTC by JulieAtInnoactive

### Description
added instructions to create new step when workflow is emty

https://user-images.githubusercontent.com/69463260/102787211-02c20f00-43a1-11eb-805d-97fad7107b84.mp4

**Fixes**: # (issue)

### Type of change

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:

### Aditional Notes

### Checklist

- [ ] My code follows the [Coding Conventions](#coding-conventions)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2020-12-22 20:18 UTC, Maxsiom commented
Your Pull Request seems to be based on Simon's Pull Request #233
You can fix this by:

1. `git fetch`
2. `git rebase -i origin/develop`
3. Instead of _"pick"_, use "drop" in front of commit **2d3987d**
4. Then rewrite the commit message (your commits will be merged into one commit)
5. If it was successful, use the following command: `git push --force-with-lease`

Then it should be fixed. :)

2020-12-22 20:23 UTC, Maxsiom requested changes

2020-12-22 20:23 UTC, Maxsiom commented on Editor/UI/Windows/CourseWindowFixedOverlay.cs
> +
```suggestion
```

[Coding Conventions](https://github.com/Innoactive/Creator/blob/develop/.github/CODING_CONVENTIONS.md): No unnecessary white spaces. :)

2020-12-22 20:23 UTC, Maxsiom commented on Editor/UI/Windows/CourseWindowFixedOverlay.cs
> +            IChapter c = GlobalEditorHandler.GetCurrentChapter();
```suggestion
            IChapter chapter = GlobalEditorHandler.GetCurrentChapter();
```

[Coding Conventions](https://github.com/Innoactive/Creator/blob/develop/.github/CODING_CONVENTIONS.md): Proper variable names. :)

2020-12-23 21:03 UTC, Maxsiom commented on Editor/UI/Windows/CourseWindowFixedOverlay.cs
> +using Innoactive.CreatorPro.Account;
```suggestion
```

Not needed in here and would cause exceptions for free creator users.

2020-12-23 21:04 UTC, Maxsiom commented on Editor/UI/Windows/CourseWindowFixedOverlay.cs
> +
```suggestion
/* Copyright (C) Innoactive GmbH - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Innoactive GmbH, November 2020
 */

```

Not needed. This is the core and thus free version of the Creator.

2021-01-04 13:26 UTC, JulieAtInnoactive commented
@SimonTheSourcerer would you mind to help me on Max's comment with the rebase? I am afraid to break something.

2021-01-11 13:46 UTC, tomwim requested changes
Needs rebasing as mentioned before.
Otherwise looks good and moves properly when resizing the window

2021-01-11 13:46 UTC, tomwim commented on Editor/UI/Windows/CourseWindowFixedOverlay.cs
> +            if(c != null && (c.Data.FirstStep == null && c.Data.Steps.Count == 0))
c is undefined

2021-01-11 13:46 UTC, tomwim commented on Editor/UI/Windows/CourseWindowFixedOverlay.cs
> +    internal class CourseWindowFixedOverlay : IEditorGraphicDrawer
Dont like the naming. Does not do what it says.
`CourseWindowHelperOverlay`?

2021-01-11 16:31 UTC, tomwim commented
- fixed compile error
- fixed position (now centered)
- renamed file
- cleaned up code a bit
- Rebased

Ready for review @SimonTheSourcerer

2021-01-11 21:27 UTC, Gusinuhe commented
<img width="679" alt="Screenshot 2021-01-11 at 22 25 52" src="https://user-images.githubusercontent.com/6911992/104240346-36ea9600-545c-11eb-97a0-62f8c44e077a.png">

2021-01-12 08:39 UTC, tomwim commented
Nice catch, fixed it

2021-01-12 08:53 UTC, tomwim commented
Just feel there should be a nicer way. Like an attribute or something that determines whether the `IEditorGraphicDrawer` should be drawn or not

2021-01-12 09:34 UTC, Gusinuhe approved these changes
Works like a charm👍
Code is okish as long as we don't care about documenting internal stuff (hopping none ever touch the code again).

2021-01-12 11:44 UTC, SimonTheSourcerer requested changes

2021-01-12 11:44 UTC, SimonTheSourcerer commented on Editor/UI/Windows/WorkflowInstructionOverlay.cs
> +            if (UserAccount.IsAccountLoggedIn() == false)
This will break when Pro is missing

2021-01-12 12:03 UTC, SimonTheSourcerer approved these changes

2021-01-12 12:03 UTC, merged