chore: updated maintainer
Innoactive/Creator pull request #242
Opened 2021-01-13 13:31 UTC by SimonTheSourcerer

### Description
Replaced Aleksei with Thomas as active maintainer.

2021-01-13 13:33 UTC, tomwim requested changes

2021-01-13 13:33 UTC, tomwim commented on .github/CONTRIBUTING.md
>  Meet out maintainers:
Can we fix this typo :D which is in every repository

```suggestion
Meet our maintainers:
```

2021-01-14 10:16 UTC, SimonTheSourcerer commented on .github/CONTRIBUTING.md
> +### Former Contributer
```suggestion
### Former Maintainers
```

2021-01-14 10:20 UTC, Gusinuhe approved these changes

2021-01-14 14:27 UTC, tomwim approved these changes

2021-01-14 16:01 UTC, merged