refactor: limited the usage of player input
Innoactive/Creator pull request #277
Opened 2021-04-30 12:00 UTC by SimonTheSourcerer

### Description

**Fixes**: # (issue)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:

### Aditional Notes

### Checklist

- [ ] My code follows the [Coding Conventions](#coding-conventions)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-04-30 12:12 UTC, Gusinuhe approved these changes

2021-04-30 12:12 UTC, Gusinuhe commented on Runtime/Input/InputController.cs
> +            public readonly Action<InputEventArgs> Action;
This is an API break, tbh there shouldn't be any real issue, but let's remember it.

2021-05-03 12:01 UTC, tomwim requested changes

2021-05-03 12:01 UTC, tomwim commented on Runtime/Input/DefaultInputController.cs
> +    public class DefaultInputController : InputController
Docs pls

2021-05-03 12:01 UTC, tomwim commented on Runtime/Input/InputController.cs
> +        protected struct ListenerInfo
this also would like some docs please

2021-05-03 12:15 UTC, Gusinuhe requested changes
Perhaps change the `Debug.Error` for `Exceptions` in `Editor/Input/InputEditorUtils.cs`

2021-05-03 12:15 UTC, Gusinuhe commented on Editor/Input/InputEditorUtils.cs
> +
```suggestion
```

2021-05-03 12:15 UTC, Gusinuhe commented on Editor/Input/InputEditorUtils.cs
> +
```suggestion
```

2021-05-03 12:15 UTC, Gusinuhe commented on Editor/Input/InputEditorUtils.cs
> +
```suggestion
```

2021-05-03 12:15 UTC, Gusinuhe commented on Editor/Input/InputEditorUtils.cs
> +        public static void OpenKeyBindingEdit()
```suggestion
        public static void OpenKeyBindingEditor()
```

2021-05-03 12:56 UTC, Gusinuhe submitted a review, later dismissed

2021-05-03 14:14 UTC, tomwim submitted a review, later dismissed

2021-05-03 14:14 UTC, tomwim commented on Runtime/Input/DefaultInputController.cs
> +    /// Input controller based on unity's InputSystem.
```suggestion
    /// Input controller based on Unity's InputSystem.
```

2021-05-03 14:17 UTC, tomwim approved these changes

2021-05-03 14:48 UTC, merged